-- 테이블 생성 쿼리
CREATE TABLE HECTO.NOTICE (
NOTICE_IDX NUMBER
);
COMMENT ON TABLE HECTO.NOTICE IS '공지사항 테이블';
COMMENT ON COLUMN HECTO.NOTICE.NOTICE_IDX IS '공지사항 키';

-- SEQUENCE 생성 쿼리
CREATE SEQUENCE HECTO.NOTICE_IDX_SEQ INCREMENT BY 1 MINVALUE 0 NOCYCLE NOCACHE NOORDER

-- SEQUENCE 사용 예시
-- INSERT INTO notice(notice_idx) VALUES (NOTICE_IDX_SEQ.NEXTVAL)